#!/usr/bin/env bash
# Displays informations about subdomains
# The bash script accepts 2 arguments:
#	- the domain: a mandatory string representing the domain name
#	- the subdomain: an optional string representing the subdomain name
# Output: "The subdomain [SUBDOMAIN] is a [RECORD TYPE] record and points to [DESTINATION]"
# When only the domain is provided, display information for its subdmains
# When passing the domain and the subdomain parameter, dsisplay information or the specified
# subdomain
# Must use:
#	- awk
#	- at least one Bash function
# You do not need to handle edge cases such as:
#	- Empty parameters
#	- Nonexistent domain names
#	- Nonexistent subdomains

subdomains=("www" "lb-01" "web-01" "web-02")

subdomain_info ()
{
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{
	split($1, arr, ".");
	print "The subdomain " arr[1] " is a " $4 " record and points to " $5}'
	
}

if (( "$#" == 1 ));
then
	for i in "${subdomains[@]}";
	do
		subdomain_info "$1" "$i"
	done
elif (( "$#" == 2 ));
then
	subdomain_info "$1" "$2"
fi
