#!/usr/bin/env bash
# Installing Nginx on web-server and testing it

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello Wordl!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
