#!/usr/bin/env bash
# Installing Nginx on web-server and testing it

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
