#!/usr/bin/env bash
# Setting up Nginx web server

# Install Nginx
apt-get update && apt-get install -y nginx

# Create the content of our website
echo "Hello World!" > /var/www/html/index.html

# Apply configuration and restart nginx
nginx -t
service nginx restart
