#!/usr/bin/env bash
# Configure a "301 Moved Permanently" redirection on Nginx

# When a user tries to get the page "example.com/redirect_me/",
# he gets the page provided by the url specified
# (in our script "https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4")

str="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"

sed -i "s/server_name _;/$str/" /etc/nginx/sites-available/my_website

nginx -t
service nginx restart
