#!/usr/bin/env bash
# Configure a Nginx

# Install Nginx
apt-get update && apt-get install -y nginx

echo "Hello Wordl!" | tee /var/www/html/index.html

str="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$str/" /etc/nginx/sites-available/default

nginx -t
service nginx restart

