#!/usr/bin/env bash
# Redirection with Nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

new_location='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
sudo sed -i "/server_name _;/ a \ $new_location" /etc/nginx/sites-available/default

sudo service nginx restart
