#!/usr/bin/env bash
# Configure Nginx | Redirection Nginx | Custom 404 Nginx.

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

n='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
sudo sed -i "/server_name _;/ a \ $n" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "/server_name _;/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
