#!/usr/bin/env bash
# Configure a Nginx

# Install Nginx
apt-get update && apt-get install -y nginx

echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
str="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/404.html;\n\n\tlocation = \/404.html {\n\t\tinternal;\n\t\troot \/var\/www\/html;\n\t}"

sed -i "s/server_name _;/$str/" /etc/nginx/sites-available/default

# Make HTTP response containing X-Served-By header
str="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sed -i "s/http {/$str/" /etc/nginx/nginx.conf

# Reload Nginx
nginx -t
service nginx restart
