#!/usr/bin/env bash

# Configure Nginx so that it is possible to know what server returns
# a response based on the hostname of the server.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

new_location='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
sudo sed -i "/server_name _;/ a \ $new_location" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
error="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed "/server_name _;/a\ $error" -i /etc/nginx/sites-available/default

custom_header="\n\tadd_header X-Served-By \$HOSTNAME;"
sudo sed "/server_name _;/ a\ $custom_header" -i /etc/nginx/sites-available/default

sudo service nginx restart
