#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
FILE=$(haproxy -v)
if [ ! -e "$FILE" ];
then
	sudo apt-get update -y
	sudo apt-get install haproxy=2.0.\* -y
fi

FRONTEND="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers"
BACKEND="backend web_servers\n\tbalance roundrobin\n\tserver 28996-web-01 100.27.13.223:80 check\n\tserver 28996-web-02 100.24.240.49:80 check"

CONFIG_FILE="/etc/haproxy/haproxy.cfg"
if ! grep -qF "$FRONTEND" "$CONFIG_FILE";
then
	echo -e "\n$FRONTEND" | sudo tee -a "$CONFIG_FILE"
fi

if ! grep -qF "$BACKEND" "$CONFIG_FILE";
then
	echo -e "\n$BACKEND" | sudo tee -a "$CONFIG_FILE"
fi

sudo service haproxy restart
