#!/usr/bin/env bash
# Install & Configure HAproxy
apt-get update
apt-get -y install haproxy=2.0.\*

str="\nfrontend f_devactions\n\tbind *:80\n\tmode http\n\tdefault_backend b_devactions\n\nbackend b_devactions\n\tmode http\n\tbalance roundrobin\n\tserver 28996-web-01 54.90.9.157:80 check\n\tserver 28996-web-02 52.91.209.247:80 check"
echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg

sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy

service haproxy restart
