#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it
if [ "$1" ]; then
        mysqldump -uroot -p"$1" tyrell_corp > tyrell_corp.sql
        tar -czvf "$(date +'%d-%m-%Y').tar.gz" tyrell_corp.sql
else
        echo "Somethig went wrong ! Verify your password please."
fi
