#!/usr/bin/env bash
# FizzBuzz Script: displays number from 1 to 100
# +Displays FizzBuzz when the number is a multiple of 3 and 5
# +Displays Fizz when the number is a multiple of 3
# +Displays Buzz when the number is a multiple of 5
# +Displays the number in other cases

for (( i = 1; i <= 100; i++ ))
do
	if [ $(( "$i" % 3 )) == 0 ] && [ $(( "$i" % 5 )) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $(( "$i" % 3 )) == 0 ]
	then
		echo "Fizz"
	elif [ $(( "$i" % 5 )) == 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
