#!/usr/bin/env bash
# Firewall configuration to enable only outgoing trafic and only incoming trafic for SSH, HTTP(S)
sudo apt-get update && sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
echo 'y' | sudo ufw --force enable
