#!/usr/bin/env bash
# Configures an Ubuntu server so that:
#	- localhost resolves to 127.0.0.2
#	- facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/' /etc/hosts
cp -f ~/hosts.new /etc/hosts
