#!/usr/bin/env bash
# Fixing the docker container so that Nginx is runing as the nginx user at port 8080
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080 /g' /etc/nginx/sites-enabled/default
su nginx -s /bin/bash -c 'service nginx restart'
