#!/usr/bin/env bash
# Fixing the docker container so that Nginx is runing as the nginx user at port 8080
service apache2 stop
chmod 644 /etc/nginx/nginx.conf /etc/nginx/sites-enabled/default
sed -i "s/^user .*;/user nginx;/" /etc/nginx/nginx.conf
sed -Ei "s/(listen (\[::\]:)?80) /\180 /" /etc/nginx/sites-enabled/default
su nginx -s /bin/bash -c 'service nginx restart'
